language: python

python: '3.4'
sudo: false

# We don't care about Travis' python versions, we install conda anyway
env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1


install:
  - pip install awscli

script:
  - return 0

notifications:
  email: true
