# create env from file with: conda env create -f environment.yml
# activate env with: source activate aws-environment

name: aws-environment
channels:
- defaults
- conda-forge
dependencies:
- boto3=1.4.4=py36_0
- botocore=1.5.38=py36_0
- docutils=0.13.1=py36_0
- jmespath=0.9.0=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.1=0
- python-dateutil=2.6.1=py36_0
- readline=6.2=2
- ruamel_yaml=0.11.14=py36_1
- s3transfer=0.1.10=py36_0
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - awacs==0.6.2
  - awscli==1.11.83
  - colorama==0.3.7
  - pyasn1==0.3.1
  - pyyaml==3.12
  - rsa==3.4.2
  - troposphere==1.9.3

