KEY_NAME: 'franzi'
SUBNET_WEST_1A: 'subnet-613eee06'
SUBNET_WEST_1B: 'subnet-32c41a7b'
SUBNET_WEST_1C: 'subnet-b4b9a5ec'

ec2_with_cloudwatch_agent:
  LOG_CONFIG: 's3://franziska-adler-staging/log_config'

emr:
  INSTANCE_COUNT: '2'
  WRITE_BUCKET_ARN: 'arn:aws:s3:::franziska-adler-emr*'

deepLearning_ec2:
  EC2_STACK_NAME: 'DeepLearningStack'
  STAGE: 'staging'
  WRITE_BUCKET_ARN: 'arn:aws:s3:::franziska-adler-general/*'
  INSTANCE_TYPE: 't2.nano' # for testing
  AZ_NAME: 'eu-west-1c'
  S3_KEY_JUPYTER_CONF: s3://franziska-adler-deployments/production/aws_playground/cloudformation/ec2/scripts/jupyter_notebook_config.py
  S3_KEY_INSTALL: s3://franziska-adler-deployments/production/aws_playground/cloudformation/ec2/scripts/certificate_and_s3fuse.sh

log_s3events_2_cloudwatch_lambda:
  STACK_NAME: LogS3EventsToCloudwatch
  FCT: LogS3Events2Cloudwatch
  DEPLOYMENT_BUCKET: franziska-adler-staging
  S3_KEY: lambdas/LogS3Events2Cloudwatch.zip
  WATCH_BUCKET: franziska-adler-test-bucket

statemachine_example:
  STACK_NAME: StateMachineExampleStack
  FCT: MyNewStateMachineLambdaFct
  DEPLOYMENT_BUCKET: franziska-adler-staging
  S3_KEY: lambdas/StatemachineExampleFct.zip

simple_ETL_state_machine:
  STACK_NAME: StateMachineSimpleETLStack
  DEPLOYMENT_BUCKET: franziska-adler-staging
  FCT_1: validate
  S3_KEY_1: lambdas/SimpleETLStatemachine/validate.zip

