KEY_NAME: 'franzi'
SUBNET_WEST_1A: 'subnet-613eee06'
SUBNET_WEST_1B: 'subnet-32c41a7b'
SUBNET_WEST_1C: 'subnet-b4b9a5ec'

ec2_with_cloudwatch_agent:
  LOG_CONFIG: 's3://franziska-adler-staging/log_config'

emr:
  INSTANCE_COUNT: '2'
  WRITE_BUCKET_ARN: 'arn:aws:s3:::franziska-adler-emr*'

deepLearning_ec2:
  EC2_STACK_NAME: 'DeepLearningStack'
  STAGE: 'staging'
  WRITE_BUCKET_ARN: 'arn:aws:s3:::franziska-adler-staging/*'
  INSTANCE_TYPE: 'p2.xlarge'
  AZ_NAME: 'eu-west-1c'

log_s3events_2_cloudwatch_lambda:
  STACK_NAME: LogS3PutEventsToCloudwatch
  FCT: log_s3events_2_cloudwatch
  DEPLOYMENT_BUCKET: franziska-adler-staging
  S3_KEY: 'lambdas/log_s3events_2_cloudwatch.zip'
  WATCH_BUCKET: arn:aws:s3:::franziska-adler-test-bucket

